#ddev-generated
# Install Chromium OS dependencies (version-independent).
RUN npx -y playwright install-deps chromium

# Add the mkcert certificate authority.
RUN apt-get update && apt-get install -y libnss3-tools

# Clean up to save disk space.
RUN apt-get clean && rm -rf /var/lib/apt/lists/*
