#ddev-generated
hooks:
  post-start:
    - exec: "[[ -d /var/www/html/.claude/skills/playwright-cli ]] || playwright-cli install --skills"
    - exec: mkdir -p $HOME/.pki/nssdb && certutil -d sql:$HOME/.pki/nssdb -N --empty-password && certutil -d sql:$HOME/.pki/nssdb -A -t "C,," -n mkcert-ca -i $(mkcert -CAROOT)/rootCA.pem
web_environment:
- PLAYWRIGHT_MCP_BROWSER=chromium
